Import urllib.request instead of urllib
As of January 25, 2021, in some environments, such as Colab (Python 3.6.9),
the following import statement
    import urllib
is not the right one for using urllib.request.

Indeed, calls to urllib.request functions then yield the following error:
    AttributeError: module 'urllib' has no attribute 'request'

One must import urllib.request instead.

See also https://stackoverflow.com/q/22278993